// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types/orig_types.go

package afpacket

var (
	tpV1HdrSize = 0x20
	tpV2HdrSize = 0x20
	tpV3HdrSize = 0x30
)

const (
	EtherHdrLen = 0x6
	VlanHdrLen  = 0x4
)

type (
	Cint    int32
	SockLen uint32

	TpReq struct {
		Block_size uint32
		Block_nr   uint32
		Frame_size uint32
		Frame_nr   uint32
	}
	TpV3Req struct {
		Block_size       uint32
		Block_nr         uint32
		Frame_size       uint32
		Frame_nr         uint32
		Retire_blk_tov   uint32
		Sizeof_priv      uint32
		Feature_req_word uint32
	}

	SocketStats struct {
		StatsPackets uint32
		StatsDrops   uint32
	}

	SocketStatsV3 struct {
		SocketStats
		FreezeQueueCount uint32
	}

	Timestamp struct {
		Sec  uint32
		Usec uint32
	}

	TpV1Hdr struct {
		Status    uint64
		Len       uint32
		Snaplen   uint32
		Mac       uint16
		Net       uint16
		Sec       uint32
		Usec      uint32
		Pad_cgo_0 [4]byte
	}
	TpV2Hdr struct {
		Status    uint32
		Len       uint32
		Snaplen   uint32
		Mac       uint16
		Net       uint16
		Sec       uint32
		Nsec      uint32
		Vlan_tci  uint16
		Vlan_tpid uint16
		Padding   [4]uint8
	}
	TpV3Hdr struct {
		block    *TpV3Block
		blockhdr *TpV3BlockHdr
		packet   *TpV3Packet
		used     TpV3Used
	}

	SockaddrLL = struct {
		Family   uint16
		Protocol uint16
		Ifindex  int32
		Hatype   uint16
		Pkttype  uint8
		Halen    uint8
		Addr     [8]uint8
	}
)
type (
	HeaderVariant1 struct {
		Rxhash    uint32
		Vlan_tci  uint32
		Vlan_tpid uint16
		Padding   uint16
	}
	TpV3Block struct {
		Version uint32
		To_priv uint32
		Hdr     [40]byte
	}
	TpV3BlockHdr struct {
		Block_status        uint32
		Num_pkts            uint32
		Offset_to_first_pkt uint32
		Blk_len             uint32
		Seq_num             uint64
		Ts_first_pkt        Timestamp
		Ts_last_pkt         Timestamp
	}
	TpV3Packet struct {
		Next_offset uint32
		Sec         uint32
		Nsec        uint32
		Snaplen     uint32
		Len         uint32
		Status      uint32
		Mac         uint16
		Net         uint16
		Hv1         HeaderVariant1
		Padding     [8]uint8
	}
	TpV3Used uint32
)
